//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3655
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IService1
{
    
    int getindenty(string usr, string pass);
    
    QueryRsult[] getquery(QueryArgs qargs, int pageSize, int pageIndex, string usr, string pass, out int pageCount, out int Counts);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="getindenty", Namespace="http://tempuri.org/")]
public partial class getindentyRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public string usr;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=1)]
    public string pass;
    
    public getindentyRequest()
    {
    }
    
    public getindentyRequest(string usr, string pass)
    {
        this.usr = usr;
        this.pass = pass;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="getindentyResponse", Namespace="http://tempuri.org/")]
public partial class getindentyResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=0)]
    public int getindentyResult;
    
    public getindentyResponse()
    {
    }
    
    public getindentyResponse(int getindentyResult)
    {
        this.getindentyResult = getindentyResult;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/rjtquery")]
public partial class QueryArgs
{
    
    private string barcodeField;
    
    private string batchnoField;
    
    private string prodnameField;
    
    private string prodnoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string barcode
    {
        get
        {
            return this.barcodeField;
        }
        set
        {
            this.barcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string batchno
    {
        get
        {
            return this.batchnoField;
        }
        set
        {
            this.batchnoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string prodname
    {
        get
        {
            return this.prodnameField;
        }
        set
        {
            this.prodnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string prodno
    {
        get
        {
            return this.prodnoField;
        }
        set
        {
            this.prodnoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("NetCFSvcUtil", "3.5.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/rjtquery")]
public partial class QueryRsult
{
    
    private string batchnoField;
    
    private string batchnozjField;
    
    private string depposField;
    
    private string floornoField;
    
    private double lestnumField;
    
    private bool lestnumFieldSpecified;
    
    private double lestnumzjField;
    
    private bool lestnumzjFieldSpecified;
    
    private string monadField;
    
    private string permemoField;
    
    private string prodnameField;
    
    private string prodnoField;
    
    private string prodpzwhField;
    
    private string prodsizeField;
    
    private string warenoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public string batchno
    {
        get
        {
            return this.batchnoField;
        }
        set
        {
            this.batchnoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string batchnozj
    {
        get
        {
            return this.batchnozjField;
        }
        set
        {
            this.batchnozjField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public string deppos
    {
        get
        {
            return this.depposField;
        }
        set
        {
            this.depposField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public string floorno
    {
        get
        {
            return this.floornoField;
        }
        set
        {
            this.floornoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public double lestnum
    {
        get
        {
            return this.lestnumField;
        }
        set
        {
            this.lestnumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lestnumSpecified
    {
        get
        {
            return this.lestnumFieldSpecified;
        }
        set
        {
            this.lestnumFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public double lestnumzj
    {
        get
        {
            return this.lestnumzjField;
        }
        set
        {
            this.lestnumzjField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lestnumzjSpecified
    {
        get
        {
            return this.lestnumzjFieldSpecified;
        }
        set
        {
            this.lestnumzjFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
    public string monad
    {
        get
        {
            return this.monadField;
        }
        set
        {
            this.monadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
    public string permemo
    {
        get
        {
            return this.permemoField;
        }
        set
        {
            this.permemoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
    public string prodname
    {
        get
        {
            return this.prodnameField;
        }
        set
        {
            this.prodnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
    public string prodno
    {
        get
        {
            return this.prodnoField;
        }
        set
        {
            this.prodnoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
    public string prodpzwh
    {
        get
        {
            return this.prodpzwhField;
        }
        set
        {
            this.prodpzwhField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
    public string prodsize
    {
        get
        {
            return this.prodsizeField;
        }
        set
        {
            this.prodsizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
    public string wareno
    {
        get
        {
            return this.warenoField;
        }
        set
        {
            this.warenoField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="getquery", Namespace="http://tempuri.org/")]
public partial class getqueryRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    public QueryArgs qargs;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=1)]
    public int pageSize;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=2)]
    public int pageIndex;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=3)]
    public string usr;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=4)]
    public string pass;
    
    public getqueryRequest()
    {
    }
    
    public getqueryRequest(QueryArgs qargs, int pageSize, int pageIndex, string usr, string pass)
    {
        this.qargs = qargs;
        this.pageSize = pageSize;
        this.pageIndex = pageIndex;
        this.usr = usr;
        this.pass = pass;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="getqueryResponse", Namespace="http://tempuri.org/")]
public partial class getqueryResponse
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://tempuri.org/", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/rjtquery", IsNullable=false)]
    public QueryRsult[] getqueryResult;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=1)]
    public int pageCount;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://tempuri.org/", Order=2)]
    public int Counts;
    
    public getqueryResponse()
    {
    }
    
    public getqueryResponse(QueryRsult[] getqueryResult, int pageCount, int Counts)
    {
        this.getqueryResult = getqueryResult;
        this.pageCount = pageCount;
        this.Counts = Counts;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class Service1Client : Microsoft.Tools.ServiceModel.CFClientBase<IService1>, IService1
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://l-pc/rjtquery/Service1.svc");
    
    public Service1Client() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private getindentyResponse getindenty(getindentyRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IService1/getindenty";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IService1/getindentyResponse";
        info.ResponseIsWrapped = true;
        getindentyResponse retVal = base.Invoke<getindentyRequest, getindentyResponse>(info, request);
        return retVal;
    }
    
    public int getindenty(string usr, string pass)
    {
        getindentyRequest request = new getindentyRequest(usr, pass);
        getindentyResponse response = this.getindenty(request);
        return response.getindentyResult;
    }
    
    private getqueryResponse getquery(getqueryRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://tempuri.org/IService1/getquery";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://tempuri.org/IService1/getqueryResponse";
        info.ResponseIsWrapped = true;
        getqueryResponse retVal = base.Invoke<getqueryRequest, getqueryResponse>(info, request);
        return retVal;
    }
    
    public QueryRsult[] getquery(QueryArgs qargs, int pageSize, int pageIndex, string usr, string pass, out int pageCount, out int Counts)
    {
        getqueryRequest request = new getqueryRequest(qargs, pageSize, pageIndex, usr, pass);
        getqueryResponse response = this.getquery(request);
        pageCount = response.pageCount;
        Counts = response.Counts;
        return response.getqueryResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://tempuri.org/IService1/getindenty", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IService1/getindenty", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://tempuri.org/IService1/getquery", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://tempuri.org/IService1/getquery", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://tempuri.org/IService1/getindentyResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IService1/getindentyResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://tempuri.org/IService1/getqueryResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://tempuri.org/IService1/getqueryResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
