#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3655
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rjtquery
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="rjt")]
	public partial class rjtDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertce_word(ce_word instance);
    partial void Updatece_word(ce_word instance);
    partial void Deletece_word(ce_word instance);
    partial void Insertproduct(product instance);
    partial void Updateproduct(product instance);
    partial void Deleteproduct(product instance);
    partial void Insertprod_dep(prod_dep instance);
    partial void Updateprod_dep(prod_dep instance);
    partial void Deleteprod_dep(prod_dep instance);
    partial void InsertWare_House(Ware_House instance);
    partial void UpdateWare_House(Ware_House instance);
    partial void DeleteWare_House(Ware_House instance);
    partial void Insertprod_dep_zjc(prod_dep_zjc instance);
    partial void Updateprod_dep_zjc(prod_dep_zjc instance);
    partial void Deleteprod_dep_zjc(prod_dep_zjc instance);
    #endregion
		
		public rjtDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["rjtConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public rjtDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public rjtDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public rjtDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public rjtDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ce_word> ce_word
		{
			get
			{
				return this.GetTable<ce_word>();
			}
		}
		
		public System.Data.Linq.Table<product> product
		{
			get
			{
				return this.GetTable<product>();
			}
		}
		
		public System.Data.Linq.Table<prod_dep> prod_dep
		{
			get
			{
				return this.GetTable<prod_dep>();
			}
		}
		
		public System.Data.Linq.Table<Ware_House> Ware_House
		{
			get
			{
				return this.GetTable<Ware_House>();
			}
		}
		
		public System.Data.Linq.Table<prod_dep_zjc> prod_dep_zjc
		{
			get
			{
				return this.GetTable<prod_dep_zjc>();
			}
		}
	}
	
	[Table(Name="dbo.ce_word")]
	public partial class ce_word : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _user_code;
		
		private string _user_name;
		
		private string _user_pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_codeChanging(string value);
    partial void Onuser_codeChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_passChanging(string value);
    partial void Onuser_passChanged();
    #endregion
		
		public ce_word()
		{
			OnCreated();
		}
		
		[Column(Storage="_user_code", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string user_code
		{
			get
			{
				return this._user_code;
			}
			set
			{
				if ((this._user_code != value))
				{
					this.Onuser_codeChanging(value);
					this.SendPropertyChanging();
					this._user_code = value;
					this.SendPropertyChanged("user_code");
					this.Onuser_codeChanged();
				}
			}
		}
		
		[Column(Storage="_user_name", DbType="Char(20)")]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[Column(Storage="_user_pass", DbType="Char(32)")]
		public string user_pass
		{
			get
			{
				return this._user_pass;
			}
			set
			{
				if ((this._user_pass != value))
				{
					this.Onuser_passChanging(value);
					this.SendPropertyChanging();
					this._user_pass = value;
					this.SendPropertyChanged("user_pass");
					this.Onuser_passChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.product")]
	public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _prod_no;
		
		private string _prod_name;
		
		private string _prod_size;
		
		private string _monad;
		
		private string _box_num;
		
		private string _dep_pos;
		
		private string _ware_no;
		
		private bool _recipe;
		
		private bool _sell_stop;
		
		private System.Nullable<decimal> _retail_price;
		
		private System.Nullable<decimal> _std_price;
		
		private System.Nullable<decimal> _Cuntry_Price;
		
		private System.Nullable<decimal> _corp_price;
		
		private System.Nullable<decimal> _buy_price;
		
		private string _dep_no;
		
		private System.Nullable<decimal> _dep_price;
		
		private System.Nullable<decimal> _limit_num;
		
		private System.Nullable<decimal> _up_num;
		
		private string _per_memo;
		
		private System.Nullable<decimal> _limit_price;
		
		private string _prod_memo;
		
		private string _last_add;
		
		private System.Nullable<decimal> _std_per;
		
		private System.Nullable<bool> _prod_dx;
		
		private System.Nullable<decimal> _prod_price_a;
		
		private System.Nullable<decimal> _prod_price_b;
		
		private System.Nullable<decimal> _prod_price_c;
		
		private string _price_type;
		
		private System.Nullable<decimal> _prod_price_d;
		
		private decimal _prod_price_e;
		
		private string _prod_made;
		
		private string _prod_label;
		
		private string _prod_pzwh;
		
		private string _box_midnum;
		
		private string _bar_code;
		
		private string _avail_length;
		
		private string _prod_otc;
		
		private byte _yhbz;
		
		private decimal _pzjj;
		
		private byte _kssbz;
		
		private System.Nullable<int> _ps_pc;
		
		private System.Nullable<int> _ps_xh;
		
		private System.Nullable<decimal> _retail_price1;
		
		private System.Nullable<decimal> _retail_price2;
		
		private System.Nullable<decimal> _cli_up_num;
		
		private string _hdsj;
		
		private string _hdfa;
		
		private string _prod_no_tmp;
		
		private string _prod_no_old;
		
		private string _prod_no_new;
		
		private char _lzbz;
		
		private string _com_jc;
		
		private string _prod_pre;
		
		private string _prod_name2;
		
		private char _inv_lx;
		
		private System.DateTime _zp_beg_date;
		
		private System.DateTime _zp_end_date;
		
		private string _zp_memo;
		
		private string _prod_flow;
		
		private decimal _sjc_num;
		
		private decimal _sjc_num_up;
		
		private System.Nullable<decimal> _prod_price_db;
		
		private decimal _ys_bl;
		
		private decimal _prod_price_bh;
		
		private System.DateTime _upd_time;
		
		private System.DateTime _upd_price_time;
		
		private decimal _bh_pl;
		
		private bool _sell_limit;
		
		private System.DateTime _pzwh_date;
		
		private string _prod_bz;
		
		private System.DateTime _zcz_availdate;
		
		private bool _jkpw;
		
		private decimal _fl_price;
		
		private string _zyps_bm;
		
		private string _prod_area_no;
		
		private string _storage_condition;
		
		private decimal _prod_price_4;
		
		private decimal _prod_price_5;
		
		private decimal _prod_price_6;
		
		private string _prod_area_gys;
		
		private decimal _prod_gfs;
		
		private string _prod_xkzh;
		
		private string _prod_yyzzh;
		
		private string _prod_gmpzh;
		
		private string _prod_rzsjxq;
		
		private string _prod_xpmsqk;
		
		private string _prod_sqly;
		
		private string _prod_cgkyj;
		
		private string _prod_zgkyj;
		
		private string _prod_zlfzr;
		
		private string _prod_sdkhr;
		
		private string _prod_kcjl;
		
		private string _prod_wssh;
		
		private byte _all_permmit;
		
		private string _prod_type_no;
		
		private EntitySet<prod_dep> _prod_dep;
		
		private EntitySet<prod_dep_zjc> _prod_dep_zjc;
		
		private EntityRef<Ware_House> _Ware_House;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprod_noChanging(string value);
    partial void Onprod_noChanged();
    partial void Onprod_nameChanging(string value);
    partial void Onprod_nameChanged();
    partial void Onprod_sizeChanging(string value);
    partial void Onprod_sizeChanged();
    partial void OnmonadChanging(string value);
    partial void OnmonadChanged();
    partial void Onbox_numChanging(string value);
    partial void Onbox_numChanged();
    partial void Ondep_posChanging(string value);
    partial void Ondep_posChanged();
    partial void Onware_noChanging(string value);
    partial void Onware_noChanged();
    partial void OnrecipeChanging(bool value);
    partial void OnrecipeChanged();
    partial void Onsell_stopChanging(bool value);
    partial void Onsell_stopChanged();
    partial void Onretail_priceChanging(System.Nullable<decimal> value);
    partial void Onretail_priceChanged();
    partial void Onstd_priceChanging(System.Nullable<decimal> value);
    partial void Onstd_priceChanged();
    partial void OnCuntry_PriceChanging(System.Nullable<decimal> value);
    partial void OnCuntry_PriceChanged();
    partial void Oncorp_priceChanging(System.Nullable<decimal> value);
    partial void Oncorp_priceChanged();
    partial void Onbuy_priceChanging(System.Nullable<decimal> value);
    partial void Onbuy_priceChanged();
    partial void Ondep_noChanging(string value);
    partial void Ondep_noChanged();
    partial void Ondep_priceChanging(System.Nullable<decimal> value);
    partial void Ondep_priceChanged();
    partial void Onlimit_numChanging(System.Nullable<decimal> value);
    partial void Onlimit_numChanged();
    partial void Onup_numChanging(System.Nullable<decimal> value);
    partial void Onup_numChanged();
    partial void Onper_memoChanging(string value);
    partial void Onper_memoChanged();
    partial void Onlimit_priceChanging(System.Nullable<decimal> value);
    partial void Onlimit_priceChanged();
    partial void Onprod_memoChanging(string value);
    partial void Onprod_memoChanged();
    partial void Onlast_addChanging(string value);
    partial void Onlast_addChanged();
    partial void Onstd_perChanging(System.Nullable<decimal> value);
    partial void Onstd_perChanged();
    partial void Onprod_dxChanging(System.Nullable<bool> value);
    partial void Onprod_dxChanged();
    partial void Onprod_price_aChanging(System.Nullable<decimal> value);
    partial void Onprod_price_aChanged();
    partial void Onprod_price_bChanging(System.Nullable<decimal> value);
    partial void Onprod_price_bChanged();
    partial void Onprod_price_cChanging(System.Nullable<decimal> value);
    partial void Onprod_price_cChanged();
    partial void Onprice_typeChanging(string value);
    partial void Onprice_typeChanged();
    partial void Onprod_price_dChanging(System.Nullable<decimal> value);
    partial void Onprod_price_dChanged();
    partial void Onprod_price_eChanging(decimal value);
    partial void Onprod_price_eChanged();
    partial void Onprod_madeChanging(string value);
    partial void Onprod_madeChanged();
    partial void Onprod_labelChanging(string value);
    partial void Onprod_labelChanged();
    partial void Onprod_pzwhChanging(string value);
    partial void Onprod_pzwhChanged();
    partial void Onbox_midnumChanging(string value);
    partial void Onbox_midnumChanged();
    partial void Onbar_codeChanging(string value);
    partial void Onbar_codeChanged();
    partial void Onavail_lengthChanging(string value);
    partial void Onavail_lengthChanged();
    partial void Onprod_otcChanging(string value);
    partial void Onprod_otcChanged();
    partial void OnyhbzChanging(byte value);
    partial void OnyhbzChanged();
    partial void OnpzjjChanging(decimal value);
    partial void OnpzjjChanged();
    partial void OnkssbzChanging(byte value);
    partial void OnkssbzChanged();
    partial void Onps_pcChanging(System.Nullable<int> value);
    partial void Onps_pcChanged();
    partial void Onps_xhChanging(System.Nullable<int> value);
    partial void Onps_xhChanged();
    partial void Onretail_price1Changing(System.Nullable<decimal> value);
    partial void Onretail_price1Changed();
    partial void Onretail_price2Changing(System.Nullable<decimal> value);
    partial void Onretail_price2Changed();
    partial void Oncli_up_numChanging(System.Nullable<decimal> value);
    partial void Oncli_up_numChanged();
    partial void OnhdsjChanging(string value);
    partial void OnhdsjChanged();
    partial void OnhdfaChanging(string value);
    partial void OnhdfaChanged();
    partial void Onprod_no_tmpChanging(string value);
    partial void Onprod_no_tmpChanged();
    partial void Onprod_no_oldChanging(string value);
    partial void Onprod_no_oldChanged();
    partial void Onprod_no_newChanging(string value);
    partial void Onprod_no_newChanged();
    partial void OnlzbzChanging(char value);
    partial void OnlzbzChanged();
    partial void Oncom_jcChanging(string value);
    partial void Oncom_jcChanged();
    partial void Onprod_preChanging(string value);
    partial void Onprod_preChanged();
    partial void Onprod_name2Changing(string value);
    partial void Onprod_name2Changed();
    partial void Oninv_lxChanging(char value);
    partial void Oninv_lxChanged();
    partial void Onzp_beg_dateChanging(System.DateTime value);
    partial void Onzp_beg_dateChanged();
    partial void Onzp_end_dateChanging(System.DateTime value);
    partial void Onzp_end_dateChanged();
    partial void Onzp_memoChanging(string value);
    partial void Onzp_memoChanged();
    partial void Onprod_flowChanging(string value);
    partial void Onprod_flowChanged();
    partial void Onsjc_numChanging(decimal value);
    partial void Onsjc_numChanged();
    partial void Onsjc_num_upChanging(decimal value);
    partial void Onsjc_num_upChanged();
    partial void Onprod_price_dbChanging(System.Nullable<decimal> value);
    partial void Onprod_price_dbChanged();
    partial void Onys_blChanging(decimal value);
    partial void Onys_blChanged();
    partial void Onprod_price_bhChanging(decimal value);
    partial void Onprod_price_bhChanged();
    partial void Onupd_timeChanging(System.DateTime value);
    partial void Onupd_timeChanged();
    partial void Onupd_price_timeChanging(System.DateTime value);
    partial void Onupd_price_timeChanged();
    partial void Onbh_plChanging(decimal value);
    partial void Onbh_plChanged();
    partial void Onsell_limitChanging(bool value);
    partial void Onsell_limitChanged();
    partial void Onpzwh_dateChanging(System.DateTime value);
    partial void Onpzwh_dateChanged();
    partial void Onprod_bzChanging(string value);
    partial void Onprod_bzChanged();
    partial void Onzcz_availdateChanging(System.DateTime value);
    partial void Onzcz_availdateChanged();
    partial void OnjkpwChanging(bool value);
    partial void OnjkpwChanged();
    partial void Onfl_priceChanging(decimal value);
    partial void Onfl_priceChanged();
    partial void Onzyps_bmChanging(string value);
    partial void Onzyps_bmChanged();
    partial void Onprod_area_noChanging(string value);
    partial void Onprod_area_noChanged();
    partial void Onstorage_conditionChanging(string value);
    partial void Onstorage_conditionChanged();
    partial void Onprod_price_4Changing(decimal value);
    partial void Onprod_price_4Changed();
    partial void Onprod_price_5Changing(decimal value);
    partial void Onprod_price_5Changed();
    partial void Onprod_price_6Changing(decimal value);
    partial void Onprod_price_6Changed();
    partial void Onprod_area_gysChanging(string value);
    partial void Onprod_area_gysChanged();
    partial void Onprod_gfsChanging(decimal value);
    partial void Onprod_gfsChanged();
    partial void Onprod_xkzhChanging(string value);
    partial void Onprod_xkzhChanged();
    partial void Onprod_yyzzhChanging(string value);
    partial void Onprod_yyzzhChanged();
    partial void Onprod_gmpzhChanging(string value);
    partial void Onprod_gmpzhChanged();
    partial void Onprod_rzsjxqChanging(string value);
    partial void Onprod_rzsjxqChanged();
    partial void Onprod_xpmsqkChanging(string value);
    partial void Onprod_xpmsqkChanged();
    partial void Onprod_sqlyChanging(string value);
    partial void Onprod_sqlyChanged();
    partial void Onprod_cgkyjChanging(string value);
    partial void Onprod_cgkyjChanged();
    partial void Onprod_zgkyjChanging(string value);
    partial void Onprod_zgkyjChanged();
    partial void Onprod_zlfzrChanging(string value);
    partial void Onprod_zlfzrChanged();
    partial void Onprod_sdkhrChanging(string value);
    partial void Onprod_sdkhrChanged();
    partial void Onprod_kcjlChanging(string value);
    partial void Onprod_kcjlChanged();
    partial void Onprod_wsshChanging(string value);
    partial void Onprod_wsshChanged();
    partial void Onall_permmitChanging(byte value);
    partial void Onall_permmitChanged();
    partial void Onprod_type_noChanging(string value);
    partial void Onprod_type_noChanged();
    #endregion
		
		public product()
		{
			this._prod_dep = new EntitySet<prod_dep>(new Action<prod_dep>(this.attach_prod_dep), new Action<prod_dep>(this.detach_prod_dep));
			this._prod_dep_zjc = new EntitySet<prod_dep_zjc>(new Action<prod_dep_zjc>(this.attach_prod_dep_zjc), new Action<prod_dep_zjc>(this.detach_prod_dep_zjc));
			this._Ware_House = default(EntityRef<Ware_House>);
			OnCreated();
		}
		
		[Column(Storage="_prod_no", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string prod_no
		{
			get
			{
				return this._prod_no;
			}
			set
			{
				if ((this._prod_no != value))
				{
					this.Onprod_noChanging(value);
					this.SendPropertyChanging();
					this._prod_no = value;
					this.SendPropertyChanged("prod_no");
					this.Onprod_noChanged();
				}
			}
		}
		
		[Column(Storage="_prod_name", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string prod_name
		{
			get
			{
				return this._prod_name;
			}
			set
			{
				if ((this._prod_name != value))
				{
					this.Onprod_nameChanging(value);
					this.SendPropertyChanging();
					this._prod_name = value;
					this.SendPropertyChanged("prod_name");
					this.Onprod_nameChanged();
				}
			}
		}
		
		[Column(Storage="_prod_size", DbType="Char(20)")]
		public string prod_size
		{
			get
			{
				return this._prod_size;
			}
			set
			{
				if ((this._prod_size != value))
				{
					this.Onprod_sizeChanging(value);
					this.SendPropertyChanging();
					this._prod_size = value;
					this.SendPropertyChanged("prod_size");
					this.Onprod_sizeChanged();
				}
			}
		}
		
		[Column(Storage="_monad", DbType="Char(4)")]
		public string monad
		{
			get
			{
				return this._monad;
			}
			set
			{
				if ((this._monad != value))
				{
					this.OnmonadChanging(value);
					this.SendPropertyChanging();
					this._monad = value;
					this.SendPropertyChanged("monad");
					this.OnmonadChanged();
				}
			}
		}
		
		[Column(Storage="_box_num", DbType="Char(20)")]
		public string box_num
		{
			get
			{
				return this._box_num;
			}
			set
			{
				if ((this._box_num != value))
				{
					this.Onbox_numChanging(value);
					this.SendPropertyChanging();
					this._box_num = value;
					this.SendPropertyChanged("box_num");
					this.Onbox_numChanged();
				}
			}
		}
		
		[Column(Storage="_dep_pos", DbType="Char(10)")]
		public string dep_pos
		{
			get
			{
				return this._dep_pos;
			}
			set
			{
				if ((this._dep_pos != value))
				{
					this.Ondep_posChanging(value);
					this.SendPropertyChanging();
					this._dep_pos = value;
					this.SendPropertyChanged("dep_pos");
					this.Ondep_posChanged();
				}
			}
		}
		
		[Column(Storage="_ware_no", DbType="Char(3) NOT NULL", CanBeNull=false)]
		public string ware_no
		{
			get
			{
				return this._ware_no;
			}
			set
			{
				if ((this._ware_no != value))
				{
					if (this._Ware_House.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onware_noChanging(value);
					this.SendPropertyChanging();
					this._ware_no = value;
					this.SendPropertyChanged("ware_no");
					this.Onware_noChanged();
				}
			}
		}
		
		[Column(Storage="_recipe", DbType="Bit NOT NULL")]
		public bool recipe
		{
			get
			{
				return this._recipe;
			}
			set
			{
				if ((this._recipe != value))
				{
					this.OnrecipeChanging(value);
					this.SendPropertyChanging();
					this._recipe = value;
					this.SendPropertyChanged("recipe");
					this.OnrecipeChanged();
				}
			}
		}
		
		[Column(Storage="_sell_stop", DbType="Bit NOT NULL")]
		public bool sell_stop
		{
			get
			{
				return this._sell_stop;
			}
			set
			{
				if ((this._sell_stop != value))
				{
					this.Onsell_stopChanging(value);
					this.SendPropertyChanging();
					this._sell_stop = value;
					this.SendPropertyChanged("sell_stop");
					this.Onsell_stopChanged();
				}
			}
		}
		
		[Column(Storage="_retail_price", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> retail_price
		{
			get
			{
				return this._retail_price;
			}
			set
			{
				if ((this._retail_price != value))
				{
					this.Onretail_priceChanging(value);
					this.SendPropertyChanging();
					this._retail_price = value;
					this.SendPropertyChanged("retail_price");
					this.Onretail_priceChanged();
				}
			}
		}
		
		[Column(Storage="_std_price", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> std_price
		{
			get
			{
				return this._std_price;
			}
			set
			{
				if ((this._std_price != value))
				{
					this.Onstd_priceChanging(value);
					this.SendPropertyChanging();
					this._std_price = value;
					this.SendPropertyChanged("std_price");
					this.Onstd_priceChanged();
				}
			}
		}
		
		[Column(Storage="_Cuntry_Price", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> Cuntry_Price
		{
			get
			{
				return this._Cuntry_Price;
			}
			set
			{
				if ((this._Cuntry_Price != value))
				{
					this.OnCuntry_PriceChanging(value);
					this.SendPropertyChanging();
					this._Cuntry_Price = value;
					this.SendPropertyChanged("Cuntry_Price");
					this.OnCuntry_PriceChanged();
				}
			}
		}
		
		[Column(Storage="_corp_price", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> corp_price
		{
			get
			{
				return this._corp_price;
			}
			set
			{
				if ((this._corp_price != value))
				{
					this.Oncorp_priceChanging(value);
					this.SendPropertyChanging();
					this._corp_price = value;
					this.SendPropertyChanged("corp_price");
					this.Oncorp_priceChanged();
				}
			}
		}
		
		[Column(Storage="_buy_price", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> buy_price
		{
			get
			{
				return this._buy_price;
			}
			set
			{
				if ((this._buy_price != value))
				{
					this.Onbuy_priceChanging(value);
					this.SendPropertyChanging();
					this._buy_price = value;
					this.SendPropertyChanged("buy_price");
					this.Onbuy_priceChanged();
				}
			}
		}
		
		[Column(Storage="_dep_no", DbType="Char(16)")]
		public string dep_no
		{
			get
			{
				return this._dep_no;
			}
			set
			{
				if ((this._dep_no != value))
				{
					this.Ondep_noChanging(value);
					this.SendPropertyChanging();
					this._dep_no = value;
					this.SendPropertyChanged("dep_no");
					this.Ondep_noChanged();
				}
			}
		}
		
		[Column(Storage="_dep_price", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> dep_price
		{
			get
			{
				return this._dep_price;
			}
			set
			{
				if ((this._dep_price != value))
				{
					this.Ondep_priceChanging(value);
					this.SendPropertyChanging();
					this._dep_price = value;
					this.SendPropertyChanged("dep_price");
					this.Ondep_priceChanged();
				}
			}
		}
		
		[Column(Storage="_limit_num", DbType="Decimal(9,3)")]
		public System.Nullable<decimal> limit_num
		{
			get
			{
				return this._limit_num;
			}
			set
			{
				if ((this._limit_num != value))
				{
					this.Onlimit_numChanging(value);
					this.SendPropertyChanging();
					this._limit_num = value;
					this.SendPropertyChanged("limit_num");
					this.Onlimit_numChanged();
				}
			}
		}
		
		[Column(Storage="_up_num", DbType="Decimal(9,3)")]
		public System.Nullable<decimal> up_num
		{
			get
			{
				return this._up_num;
			}
			set
			{
				if ((this._up_num != value))
				{
					this.Onup_numChanging(value);
					this.SendPropertyChanging();
					this._up_num = value;
					this.SendPropertyChanged("up_num");
					this.Onup_numChanged();
				}
			}
		}
		
		[Column(Storage="_per_memo", DbType="Char(18)")]
		public string per_memo
		{
			get
			{
				return this._per_memo;
			}
			set
			{
				if ((this._per_memo != value))
				{
					this.Onper_memoChanging(value);
					this.SendPropertyChanging();
					this._per_memo = value;
					this.SendPropertyChanged("per_memo");
					this.Onper_memoChanged();
				}
			}
		}
		
		[Column(Storage="_limit_price", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> limit_price
		{
			get
			{
				return this._limit_price;
			}
			set
			{
				if ((this._limit_price != value))
				{
					this.Onlimit_priceChanging(value);
					this.SendPropertyChanging();
					this._limit_price = value;
					this.SendPropertyChanged("limit_price");
					this.Onlimit_priceChanged();
				}
			}
		}
		
		[Column(Storage="_prod_memo", DbType="Char(50)")]
		public string prod_memo
		{
			get
			{
				return this._prod_memo;
			}
			set
			{
				if ((this._prod_memo != value))
				{
					this.Onprod_memoChanging(value);
					this.SendPropertyChanging();
					this._prod_memo = value;
					this.SendPropertyChanged("prod_memo");
					this.Onprod_memoChanged();
				}
			}
		}
		
		[Column(Storage="_last_add", DbType="Char(12) NOT NULL", CanBeNull=false)]
		public string last_add
		{
			get
			{
				return this._last_add;
			}
			set
			{
				if ((this._last_add != value))
				{
					this.Onlast_addChanging(value);
					this.SendPropertyChanging();
					this._last_add = value;
					this.SendPropertyChanged("last_add");
					this.Onlast_addChanged();
				}
			}
		}
		
		[Column(Storage="_std_per", DbType="Decimal(8,3)")]
		public System.Nullable<decimal> std_per
		{
			get
			{
				return this._std_per;
			}
			set
			{
				if ((this._std_per != value))
				{
					this.Onstd_perChanging(value);
					this.SendPropertyChanging();
					this._std_per = value;
					this.SendPropertyChanged("std_per");
					this.Onstd_perChanged();
				}
			}
		}
		
		[Column(Storage="_prod_dx", DbType="Bit")]
		public System.Nullable<bool> prod_dx
		{
			get
			{
				return this._prod_dx;
			}
			set
			{
				if ((this._prod_dx != value))
				{
					this.Onprod_dxChanging(value);
					this.SendPropertyChanging();
					this._prod_dx = value;
					this.SendPropertyChanged("prod_dx");
					this.Onprod_dxChanged();
				}
			}
		}
		
		[Column(Storage="_prod_price_a", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> prod_price_a
		{
			get
			{
				return this._prod_price_a;
			}
			set
			{
				if ((this._prod_price_a != value))
				{
					this.Onprod_price_aChanging(value);
					this.SendPropertyChanging();
					this._prod_price_a = value;
					this.SendPropertyChanged("prod_price_a");
					this.Onprod_price_aChanged();
				}
			}
		}
		
		[Column(Storage="_prod_price_b", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> prod_price_b
		{
			get
			{
				return this._prod_price_b;
			}
			set
			{
				if ((this._prod_price_b != value))
				{
					this.Onprod_price_bChanging(value);
					this.SendPropertyChanging();
					this._prod_price_b = value;
					this.SendPropertyChanged("prod_price_b");
					this.Onprod_price_bChanged();
				}
			}
		}
		
		[Column(Storage="_prod_price_c", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> prod_price_c
		{
			get
			{
				return this._prod_price_c;
			}
			set
			{
				if ((this._prod_price_c != value))
				{
					this.Onprod_price_cChanging(value);
					this.SendPropertyChanging();
					this._prod_price_c = value;
					this.SendPropertyChanged("prod_price_c");
					this.Onprod_price_cChanged();
				}
			}
		}
		
		[Column(Storage="_price_type", DbType="Char(4)")]
		public string price_type
		{
			get
			{
				return this._price_type;
			}
			set
			{
				if ((this._price_type != value))
				{
					this.Onprice_typeChanging(value);
					this.SendPropertyChanging();
					this._price_type = value;
					this.SendPropertyChanged("price_type");
					this.Onprice_typeChanged();
				}
			}
		}
		
		[Column(Storage="_prod_price_d", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> prod_price_d
		{
			get
			{
				return this._prod_price_d;
			}
			set
			{
				if ((this._prod_price_d != value))
				{
					this.Onprod_price_dChanging(value);
					this.SendPropertyChanging();
					this._prod_price_d = value;
					this.SendPropertyChanged("prod_price_d");
					this.Onprod_price_dChanged();
				}
			}
		}
		
		[Column(Storage="_prod_price_e", DbType="Decimal(8,2) NOT NULL")]
		public decimal prod_price_e
		{
			get
			{
				return this._prod_price_e;
			}
			set
			{
				if ((this._prod_price_e != value))
				{
					this.Onprod_price_eChanging(value);
					this.SendPropertyChanging();
					this._prod_price_e = value;
					this.SendPropertyChanged("prod_price_e");
					this.Onprod_price_eChanged();
				}
			}
		}
		
		[Column(Storage="_prod_made", DbType="Char(64)")]
		public string prod_made
		{
			get
			{
				return this._prod_made;
			}
			set
			{
				if ((this._prod_made != value))
				{
					this.Onprod_madeChanging(value);
					this.SendPropertyChanging();
					this._prod_made = value;
					this.SendPropertyChanged("prod_made");
					this.Onprod_madeChanged();
				}
			}
		}
		
		[Column(Storage="_prod_label", DbType="Char(16)")]
		public string prod_label
		{
			get
			{
				return this._prod_label;
			}
			set
			{
				if ((this._prod_label != value))
				{
					this.Onprod_labelChanging(value);
					this.SendPropertyChanging();
					this._prod_label = value;
					this.SendPropertyChanged("prod_label");
					this.Onprod_labelChanged();
				}
			}
		}
		
		[Column(Storage="_prod_pzwh", DbType="Char(64)")]
		public string prod_pzwh
		{
			get
			{
				return this._prod_pzwh;
			}
			set
			{
				if ((this._prod_pzwh != value))
				{
					this.Onprod_pzwhChanging(value);
					this.SendPropertyChanging();
					this._prod_pzwh = value;
					this.SendPropertyChanged("prod_pzwh");
					this.Onprod_pzwhChanged();
				}
			}
		}
		
		[Column(Storage="_box_midnum", DbType="Char(20)")]
		public string box_midnum
		{
			get
			{
				return this._box_midnum;
			}
			set
			{
				if ((this._box_midnum != value))
				{
					this.Onbox_midnumChanging(value);
					this.SendPropertyChanging();
					this._box_midnum = value;
					this.SendPropertyChanged("box_midnum");
					this.Onbox_midnumChanged();
				}
			}
		}
		
		[Column(Storage="_bar_code", DbType="VarChar(64)")]
		public string bar_code
		{
			get
			{
				return this._bar_code;
			}
			set
			{
				if ((this._bar_code != value))
				{
					this.Onbar_codeChanging(value);
					this.SendPropertyChanging();
					this._bar_code = value;
					this.SendPropertyChanged("bar_code");
					this.Onbar_codeChanged();
				}
			}
		}
		
		[Column(Storage="_avail_length", DbType="Char(20)")]
		public string avail_length
		{
			get
			{
				return this._avail_length;
			}
			set
			{
				if ((this._avail_length != value))
				{
					this.Onavail_lengthChanging(value);
					this.SendPropertyChanging();
					this._avail_length = value;
					this.SendPropertyChanged("avail_length");
					this.Onavail_lengthChanged();
				}
			}
		}
		
		[Column(Storage="_prod_otc", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string prod_otc
		{
			get
			{
				return this._prod_otc;
			}
			set
			{
				if ((this._prod_otc != value))
				{
					this.Onprod_otcChanging(value);
					this.SendPropertyChanging();
					this._prod_otc = value;
					this.SendPropertyChanged("prod_otc");
					this.Onprod_otcChanged();
				}
			}
		}
		
		[Column(Storage="_yhbz", DbType="TinyInt NOT NULL")]
		public byte yhbz
		{
			get
			{
				return this._yhbz;
			}
			set
			{
				if ((this._yhbz != value))
				{
					this.OnyhbzChanging(value);
					this.SendPropertyChanging();
					this._yhbz = value;
					this.SendPropertyChanged("yhbz");
					this.OnyhbzChanged();
				}
			}
		}
		
		[Column(Storage="_pzjj", DbType="Decimal(8,2) NOT NULL")]
		public decimal pzjj
		{
			get
			{
				return this._pzjj;
			}
			set
			{
				if ((this._pzjj != value))
				{
					this.OnpzjjChanging(value);
					this.SendPropertyChanging();
					this._pzjj = value;
					this.SendPropertyChanged("pzjj");
					this.OnpzjjChanged();
				}
			}
		}
		
		[Column(Storage="_kssbz", DbType="TinyInt NOT NULL")]
		public byte kssbz
		{
			get
			{
				return this._kssbz;
			}
			set
			{
				if ((this._kssbz != value))
				{
					this.OnkssbzChanging(value);
					this.SendPropertyChanging();
					this._kssbz = value;
					this.SendPropertyChanged("kssbz");
					this.OnkssbzChanged();
				}
			}
		}
		
		[Column(Storage="_ps_pc", DbType="Int")]
		public System.Nullable<int> ps_pc
		{
			get
			{
				return this._ps_pc;
			}
			set
			{
				if ((this._ps_pc != value))
				{
					this.Onps_pcChanging(value);
					this.SendPropertyChanging();
					this._ps_pc = value;
					this.SendPropertyChanged("ps_pc");
					this.Onps_pcChanged();
				}
			}
		}
		
		[Column(Storage="_ps_xh", DbType="Int")]
		public System.Nullable<int> ps_xh
		{
			get
			{
				return this._ps_xh;
			}
			set
			{
				if ((this._ps_xh != value))
				{
					this.Onps_xhChanging(value);
					this.SendPropertyChanging();
					this._ps_xh = value;
					this.SendPropertyChanged("ps_xh");
					this.Onps_xhChanged();
				}
			}
		}
		
		[Column(Storage="_retail_price1", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> retail_price1
		{
			get
			{
				return this._retail_price1;
			}
			set
			{
				if ((this._retail_price1 != value))
				{
					this.Onretail_price1Changing(value);
					this.SendPropertyChanging();
					this._retail_price1 = value;
					this.SendPropertyChanged("retail_price1");
					this.Onretail_price1Changed();
				}
			}
		}
		
		[Column(Storage="_retail_price2", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> retail_price2
		{
			get
			{
				return this._retail_price2;
			}
			set
			{
				if ((this._retail_price2 != value))
				{
					this.Onretail_price2Changing(value);
					this.SendPropertyChanging();
					this._retail_price2 = value;
					this.SendPropertyChanged("retail_price2");
					this.Onretail_price2Changed();
				}
			}
		}
		
		[Column(Storage="_cli_up_num", DbType="Decimal(9,3)")]
		public System.Nullable<decimal> cli_up_num
		{
			get
			{
				return this._cli_up_num;
			}
			set
			{
				if ((this._cli_up_num != value))
				{
					this.Oncli_up_numChanging(value);
					this.SendPropertyChanging();
					this._cli_up_num = value;
					this.SendPropertyChanged("cli_up_num");
					this.Oncli_up_numChanged();
				}
			}
		}
		
		[Column(Storage="_hdsj", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string hdsj
		{
			get
			{
				return this._hdsj;
			}
			set
			{
				if ((this._hdsj != value))
				{
					this.OnhdsjChanging(value);
					this.SendPropertyChanging();
					this._hdsj = value;
					this.SendPropertyChanged("hdsj");
					this.OnhdsjChanged();
				}
			}
		}
		
		[Column(Storage="_hdfa", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string hdfa
		{
			get
			{
				return this._hdfa;
			}
			set
			{
				if ((this._hdfa != value))
				{
					this.OnhdfaChanging(value);
					this.SendPropertyChanging();
					this._hdfa = value;
					this.SendPropertyChanged("hdfa");
					this.OnhdfaChanged();
				}
			}
		}
		
		[Column(Storage="_prod_no_tmp", DbType="VarChar(8)")]
		public string prod_no_tmp
		{
			get
			{
				return this._prod_no_tmp;
			}
			set
			{
				if ((this._prod_no_tmp != value))
				{
					this.Onprod_no_tmpChanging(value);
					this.SendPropertyChanging();
					this._prod_no_tmp = value;
					this.SendPropertyChanged("prod_no_tmp");
					this.Onprod_no_tmpChanged();
				}
			}
		}
		
		[Column(Storage="_prod_no_old", DbType="VarChar(8)")]
		public string prod_no_old
		{
			get
			{
				return this._prod_no_old;
			}
			set
			{
				if ((this._prod_no_old != value))
				{
					this.Onprod_no_oldChanging(value);
					this.SendPropertyChanging();
					this._prod_no_old = value;
					this.SendPropertyChanged("prod_no_old");
					this.Onprod_no_oldChanged();
				}
			}
		}
		
		[Column(Storage="_prod_no_new", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string prod_no_new
		{
			get
			{
				return this._prod_no_new;
			}
			set
			{
				if ((this._prod_no_new != value))
				{
					this.Onprod_no_newChanging(value);
					this.SendPropertyChanging();
					this._prod_no_new = value;
					this.SendPropertyChanged("prod_no_new");
					this.Onprod_no_newChanged();
				}
			}
		}
		
		[Column(Storage="_lzbz", DbType="Char(1) NOT NULL")]
		public char lzbz
		{
			get
			{
				return this._lzbz;
			}
			set
			{
				if ((this._lzbz != value))
				{
					this.OnlzbzChanging(value);
					this.SendPropertyChanging();
					this._lzbz = value;
					this.SendPropertyChanged("lzbz");
					this.OnlzbzChanged();
				}
			}
		}
		
		[Column(Storage="_com_jc", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string com_jc
		{
			get
			{
				return this._com_jc;
			}
			set
			{
				if ((this._com_jc != value))
				{
					this.Oncom_jcChanging(value);
					this.SendPropertyChanging();
					this._com_jc = value;
					this.SendPropertyChanged("com_jc");
					this.Oncom_jcChanged();
				}
			}
		}
		
		[Column(Storage="_prod_pre", DbType="Char(6)")]
		public string prod_pre
		{
			get
			{
				return this._prod_pre;
			}
			set
			{
				if ((this._prod_pre != value))
				{
					this.Onprod_preChanging(value);
					this.SendPropertyChanging();
					this._prod_pre = value;
					this.SendPropertyChanged("prod_pre");
					this.Onprod_preChanged();
				}
			}
		}
		
		[Column(Storage="_prod_name2", DbType="Char(50)")]
		public string prod_name2
		{
			get
			{
				return this._prod_name2;
			}
			set
			{
				if ((this._prod_name2 != value))
				{
					this.Onprod_name2Changing(value);
					this.SendPropertyChanging();
					this._prod_name2 = value;
					this.SendPropertyChanged("prod_name2");
					this.Onprod_name2Changed();
				}
			}
		}
		
		[Column(Storage="_inv_lx", DbType="VarChar(1) NOT NULL")]
		public char inv_lx
		{
			get
			{
				return this._inv_lx;
			}
			set
			{
				if ((this._inv_lx != value))
				{
					this.Oninv_lxChanging(value);
					this.SendPropertyChanging();
					this._inv_lx = value;
					this.SendPropertyChanged("inv_lx");
					this.Oninv_lxChanged();
				}
			}
		}
		
		[Column(Storage="_zp_beg_date", DbType="DateTime NOT NULL")]
		public System.DateTime zp_beg_date
		{
			get
			{
				return this._zp_beg_date;
			}
			set
			{
				if ((this._zp_beg_date != value))
				{
					this.Onzp_beg_dateChanging(value);
					this.SendPropertyChanging();
					this._zp_beg_date = value;
					this.SendPropertyChanged("zp_beg_date");
					this.Onzp_beg_dateChanged();
				}
			}
		}
		
		[Column(Storage="_zp_end_date", DbType="DateTime NOT NULL")]
		public System.DateTime zp_end_date
		{
			get
			{
				return this._zp_end_date;
			}
			set
			{
				if ((this._zp_end_date != value))
				{
					this.Onzp_end_dateChanging(value);
					this.SendPropertyChanging();
					this._zp_end_date = value;
					this.SendPropertyChanged("zp_end_date");
					this.Onzp_end_dateChanged();
				}
			}
		}
		
		[Column(Storage="_zp_memo", DbType="VarChar(255)")]
		public string zp_memo
		{
			get
			{
				return this._zp_memo;
			}
			set
			{
				if ((this._zp_memo != value))
				{
					this.Onzp_memoChanging(value);
					this.SendPropertyChanging();
					this._zp_memo = value;
					this.SendPropertyChanged("zp_memo");
					this.Onzp_memoChanged();
				}
			}
		}
		
		[Column(Storage="_prod_flow", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string prod_flow
		{
			get
			{
				return this._prod_flow;
			}
			set
			{
				if ((this._prod_flow != value))
				{
					this.Onprod_flowChanging(value);
					this.SendPropertyChanging();
					this._prod_flow = value;
					this.SendPropertyChanged("prod_flow");
					this.Onprod_flowChanged();
				}
			}
		}
		
		[Column(Storage="_sjc_num", DbType="Decimal(9,3) NOT NULL")]
		public decimal sjc_num
		{
			get
			{
				return this._sjc_num;
			}
			set
			{
				if ((this._sjc_num != value))
				{
					this.Onsjc_numChanging(value);
					this.SendPropertyChanging();
					this._sjc_num = value;
					this.SendPropertyChanged("sjc_num");
					this.Onsjc_numChanged();
				}
			}
		}
		
		[Column(Storage="_sjc_num_up", DbType="Decimal(9,3) NOT NULL")]
		public decimal sjc_num_up
		{
			get
			{
				return this._sjc_num_up;
			}
			set
			{
				if ((this._sjc_num_up != value))
				{
					this.Onsjc_num_upChanging(value);
					this.SendPropertyChanging();
					this._sjc_num_up = value;
					this.SendPropertyChanged("sjc_num_up");
					this.Onsjc_num_upChanged();
				}
			}
		}
		
		[Column(Storage="_prod_price_db", DbType="Decimal(9,2)")]
		public System.Nullable<decimal> prod_price_db
		{
			get
			{
				return this._prod_price_db;
			}
			set
			{
				if ((this._prod_price_db != value))
				{
					this.Onprod_price_dbChanging(value);
					this.SendPropertyChanging();
					this._prod_price_db = value;
					this.SendPropertyChanged("prod_price_db");
					this.Onprod_price_dbChanged();
				}
			}
		}
		
		[Column(Storage="_ys_bl", DbType="Decimal(5,2) NOT NULL")]
		public decimal ys_bl
		{
			get
			{
				return this._ys_bl;
			}
			set
			{
				if ((this._ys_bl != value))
				{
					this.Onys_blChanging(value);
					this.SendPropertyChanging();
					this._ys_bl = value;
					this.SendPropertyChanged("ys_bl");
					this.Onys_blChanged();
				}
			}
		}
		
		[Column(Storage="_prod_price_bh", DbType="Decimal(8,2) NOT NULL")]
		public decimal prod_price_bh
		{
			get
			{
				return this._prod_price_bh;
			}
			set
			{
				if ((this._prod_price_bh != value))
				{
					this.Onprod_price_bhChanging(value);
					this.SendPropertyChanging();
					this._prod_price_bh = value;
					this.SendPropertyChanged("prod_price_bh");
					this.Onprod_price_bhChanged();
				}
			}
		}
		
		[Column(Storage="_upd_time", DbType="DateTime NOT NULL")]
		public System.DateTime upd_time
		{
			get
			{
				return this._upd_time;
			}
			set
			{
				if ((this._upd_time != value))
				{
					this.Onupd_timeChanging(value);
					this.SendPropertyChanging();
					this._upd_time = value;
					this.SendPropertyChanged("upd_time");
					this.Onupd_timeChanged();
				}
			}
		}
		
		[Column(Storage="_upd_price_time", DbType="DateTime NOT NULL")]
		public System.DateTime upd_price_time
		{
			get
			{
				return this._upd_price_time;
			}
			set
			{
				if ((this._upd_price_time != value))
				{
					this.Onupd_price_timeChanging(value);
					this.SendPropertyChanging();
					this._upd_price_time = value;
					this.SendPropertyChanged("upd_price_time");
					this.Onupd_price_timeChanged();
				}
			}
		}
		
		[Column(Storage="_bh_pl", DbType="Decimal(9,3) NOT NULL")]
		public decimal bh_pl
		{
			get
			{
				return this._bh_pl;
			}
			set
			{
				if ((this._bh_pl != value))
				{
					this.Onbh_plChanging(value);
					this.SendPropertyChanging();
					this._bh_pl = value;
					this.SendPropertyChanged("bh_pl");
					this.Onbh_plChanged();
				}
			}
		}
		
		[Column(Storage="_sell_limit", DbType="Bit NOT NULL")]
		public bool sell_limit
		{
			get
			{
				return this._sell_limit;
			}
			set
			{
				if ((this._sell_limit != value))
				{
					this.Onsell_limitChanging(value);
					this.SendPropertyChanging();
					this._sell_limit = value;
					this.SendPropertyChanged("sell_limit");
					this.Onsell_limitChanged();
				}
			}
		}
		
		[Column(Storage="_pzwh_date", DbType="DateTime NOT NULL")]
		public System.DateTime pzwh_date
		{
			get
			{
				return this._pzwh_date;
			}
			set
			{
				if ((this._pzwh_date != value))
				{
					this.Onpzwh_dateChanging(value);
					this.SendPropertyChanging();
					this._pzwh_date = value;
					this.SendPropertyChanged("pzwh_date");
					this.Onpzwh_dateChanged();
				}
			}
		}
		
		[Column(Storage="_prod_bz", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string prod_bz
		{
			get
			{
				return this._prod_bz;
			}
			set
			{
				if ((this._prod_bz != value))
				{
					this.Onprod_bzChanging(value);
					this.SendPropertyChanging();
					this._prod_bz = value;
					this.SendPropertyChanged("prod_bz");
					this.Onprod_bzChanged();
				}
			}
		}
		
		[Column(Storage="_zcz_availdate", DbType="DateTime NOT NULL")]
		public System.DateTime zcz_availdate
		{
			get
			{
				return this._zcz_availdate;
			}
			set
			{
				if ((this._zcz_availdate != value))
				{
					this.Onzcz_availdateChanging(value);
					this.SendPropertyChanging();
					this._zcz_availdate = value;
					this.SendPropertyChanged("zcz_availdate");
					this.Onzcz_availdateChanged();
				}
			}
		}
		
		[Column(Storage="_jkpw", DbType="Bit NOT NULL")]
		public bool jkpw
		{
			get
			{
				return this._jkpw;
			}
			set
			{
				if ((this._jkpw != value))
				{
					this.OnjkpwChanging(value);
					this.SendPropertyChanging();
					this._jkpw = value;
					this.SendPropertyChanged("jkpw");
					this.OnjkpwChanged();
				}
			}
		}
		
		[Column(Storage="_fl_price", DbType="Decimal(8,2) NOT NULL")]
		public decimal fl_price
		{
			get
			{
				return this._fl_price;
			}
			set
			{
				if ((this._fl_price != value))
				{
					this.Onfl_priceChanging(value);
					this.SendPropertyChanging();
					this._fl_price = value;
					this.SendPropertyChanged("fl_price");
					this.Onfl_priceChanged();
				}
			}
		}
		
		[Column(Storage="_zyps_bm", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string zyps_bm
		{
			get
			{
				return this._zyps_bm;
			}
			set
			{
				if ((this._zyps_bm != value))
				{
					this.Onzyps_bmChanging(value);
					this.SendPropertyChanging();
					this._zyps_bm = value;
					this.SendPropertyChanged("zyps_bm");
					this.Onzyps_bmChanged();
				}
			}
		}
		
		[Column(Storage="_prod_area_no", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string prod_area_no
		{
			get
			{
				return this._prod_area_no;
			}
			set
			{
				if ((this._prod_area_no != value))
				{
					this.Onprod_area_noChanging(value);
					this.SendPropertyChanging();
					this._prod_area_no = value;
					this.SendPropertyChanged("prod_area_no");
					this.Onprod_area_noChanged();
				}
			}
		}
		
		[Column(Storage="_storage_condition", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string storage_condition
		{
			get
			{
				return this._storage_condition;
			}
			set
			{
				if ((this._storage_condition != value))
				{
					this.Onstorage_conditionChanging(value);
					this.SendPropertyChanging();
					this._storage_condition = value;
					this.SendPropertyChanged("storage_condition");
					this.Onstorage_conditionChanged();
				}
			}
		}
		
		[Column(Storage="_prod_price_4", DbType="Decimal(8,2) NOT NULL")]
		public decimal prod_price_4
		{
			get
			{
				return this._prod_price_4;
			}
			set
			{
				if ((this._prod_price_4 != value))
				{
					this.Onprod_price_4Changing(value);
					this.SendPropertyChanging();
					this._prod_price_4 = value;
					this.SendPropertyChanged("prod_price_4");
					this.Onprod_price_4Changed();
				}
			}
		}
		
		[Column(Storage="_prod_price_5", DbType="Decimal(8,2) NOT NULL")]
		public decimal prod_price_5
		{
			get
			{
				return this._prod_price_5;
			}
			set
			{
				if ((this._prod_price_5 != value))
				{
					this.Onprod_price_5Changing(value);
					this.SendPropertyChanging();
					this._prod_price_5 = value;
					this.SendPropertyChanged("prod_price_5");
					this.Onprod_price_5Changed();
				}
			}
		}
		
		[Column(Storage="_prod_price_6", DbType="Decimal(8,2) NOT NULL")]
		public decimal prod_price_6
		{
			get
			{
				return this._prod_price_6;
			}
			set
			{
				if ((this._prod_price_6 != value))
				{
					this.Onprod_price_6Changing(value);
					this.SendPropertyChanging();
					this._prod_price_6 = value;
					this.SendPropertyChanged("prod_price_6");
					this.Onprod_price_6Changed();
				}
			}
		}
		
		[Column(Storage="_prod_area_gys", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string prod_area_gys
		{
			get
			{
				return this._prod_area_gys;
			}
			set
			{
				if ((this._prod_area_gys != value))
				{
					this.Onprod_area_gysChanging(value);
					this.SendPropertyChanging();
					this._prod_area_gys = value;
					this.SendPropertyChanged("prod_area_gys");
					this.Onprod_area_gysChanged();
				}
			}
		}
		
		[Column(Storage="_prod_gfs", DbType="Decimal(8,2) NOT NULL")]
		public decimal prod_gfs
		{
			get
			{
				return this._prod_gfs;
			}
			set
			{
				if ((this._prod_gfs != value))
				{
					this.Onprod_gfsChanging(value);
					this.SendPropertyChanging();
					this._prod_gfs = value;
					this.SendPropertyChanged("prod_gfs");
					this.Onprod_gfsChanged();
				}
			}
		}
		
		[Column(Storage="_prod_xkzh", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string prod_xkzh
		{
			get
			{
				return this._prod_xkzh;
			}
			set
			{
				if ((this._prod_xkzh != value))
				{
					this.Onprod_xkzhChanging(value);
					this.SendPropertyChanging();
					this._prod_xkzh = value;
					this.SendPropertyChanged("prod_xkzh");
					this.Onprod_xkzhChanged();
				}
			}
		}
		
		[Column(Storage="_prod_yyzzh", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string prod_yyzzh
		{
			get
			{
				return this._prod_yyzzh;
			}
			set
			{
				if ((this._prod_yyzzh != value))
				{
					this.Onprod_yyzzhChanging(value);
					this.SendPropertyChanging();
					this._prod_yyzzh = value;
					this.SendPropertyChanged("prod_yyzzh");
					this.Onprod_yyzzhChanged();
				}
			}
		}
		
		[Column(Storage="_prod_gmpzh", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string prod_gmpzh
		{
			get
			{
				return this._prod_gmpzh;
			}
			set
			{
				if ((this._prod_gmpzh != value))
				{
					this.Onprod_gmpzhChanging(value);
					this.SendPropertyChanging();
					this._prod_gmpzh = value;
					this.SendPropertyChanged("prod_gmpzh");
					this.Onprod_gmpzhChanged();
				}
			}
		}
		
		[Column(Storage="_prod_rzsjxq", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string prod_rzsjxq
		{
			get
			{
				return this._prod_rzsjxq;
			}
			set
			{
				if ((this._prod_rzsjxq != value))
				{
					this.Onprod_rzsjxqChanging(value);
					this.SendPropertyChanging();
					this._prod_rzsjxq = value;
					this.SendPropertyChanged("prod_rzsjxq");
					this.Onprod_rzsjxqChanged();
				}
			}
		}
		
		[Column(Storage="_prod_xpmsqk", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string prod_xpmsqk
		{
			get
			{
				return this._prod_xpmsqk;
			}
			set
			{
				if ((this._prod_xpmsqk != value))
				{
					this.Onprod_xpmsqkChanging(value);
					this.SendPropertyChanging();
					this._prod_xpmsqk = value;
					this.SendPropertyChanged("prod_xpmsqk");
					this.Onprod_xpmsqkChanged();
				}
			}
		}
		
		[Column(Storage="_prod_sqly", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string prod_sqly
		{
			get
			{
				return this._prod_sqly;
			}
			set
			{
				if ((this._prod_sqly != value))
				{
					this.Onprod_sqlyChanging(value);
					this.SendPropertyChanging();
					this._prod_sqly = value;
					this.SendPropertyChanged("prod_sqly");
					this.Onprod_sqlyChanged();
				}
			}
		}
		
		[Column(Storage="_prod_cgkyj", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string prod_cgkyj
		{
			get
			{
				return this._prod_cgkyj;
			}
			set
			{
				if ((this._prod_cgkyj != value))
				{
					this.Onprod_cgkyjChanging(value);
					this.SendPropertyChanging();
					this._prod_cgkyj = value;
					this.SendPropertyChanged("prod_cgkyj");
					this.Onprod_cgkyjChanged();
				}
			}
		}
		
		[Column(Storage="_prod_zgkyj", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string prod_zgkyj
		{
			get
			{
				return this._prod_zgkyj;
			}
			set
			{
				if ((this._prod_zgkyj != value))
				{
					this.Onprod_zgkyjChanging(value);
					this.SendPropertyChanging();
					this._prod_zgkyj = value;
					this.SendPropertyChanged("prod_zgkyj");
					this.Onprod_zgkyjChanged();
				}
			}
		}
		
		[Column(Storage="_prod_zlfzr", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string prod_zlfzr
		{
			get
			{
				return this._prod_zlfzr;
			}
			set
			{
				if ((this._prod_zlfzr != value))
				{
					this.Onprod_zlfzrChanging(value);
					this.SendPropertyChanging();
					this._prod_zlfzr = value;
					this.SendPropertyChanged("prod_zlfzr");
					this.Onprod_zlfzrChanged();
				}
			}
		}
		
		[Column(Storage="_prod_sdkhr", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string prod_sdkhr
		{
			get
			{
				return this._prod_sdkhr;
			}
			set
			{
				if ((this._prod_sdkhr != value))
				{
					this.Onprod_sdkhrChanging(value);
					this.SendPropertyChanging();
					this._prod_sdkhr = value;
					this.SendPropertyChanged("prod_sdkhr");
					this.Onprod_sdkhrChanged();
				}
			}
		}
		
		[Column(Storage="_prod_kcjl", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string prod_kcjl
		{
			get
			{
				return this._prod_kcjl;
			}
			set
			{
				if ((this._prod_kcjl != value))
				{
					this.Onprod_kcjlChanging(value);
					this.SendPropertyChanging();
					this._prod_kcjl = value;
					this.SendPropertyChanged("prod_kcjl");
					this.Onprod_kcjlChanged();
				}
			}
		}
		
		[Column(Storage="_prod_wssh", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string prod_wssh
		{
			get
			{
				return this._prod_wssh;
			}
			set
			{
				if ((this._prod_wssh != value))
				{
					this.Onprod_wsshChanging(value);
					this.SendPropertyChanging();
					this._prod_wssh = value;
					this.SendPropertyChanged("prod_wssh");
					this.Onprod_wsshChanged();
				}
			}
		}
		
		[Column(Storage="_all_permmit", DbType="TinyInt NOT NULL")]
		public byte all_permmit
		{
			get
			{
				return this._all_permmit;
			}
			set
			{
				if ((this._all_permmit != value))
				{
					this.Onall_permmitChanging(value);
					this.SendPropertyChanging();
					this._all_permmit = value;
					this.SendPropertyChanged("all_permmit");
					this.Onall_permmitChanged();
				}
			}
		}
		
		[Column(Storage="_prod_type_no", DbType="Char(10)")]
		public string prod_type_no
		{
			get
			{
				return this._prod_type_no;
			}
			set
			{
				if ((this._prod_type_no != value))
				{
					this.Onprod_type_noChanging(value);
					this.SendPropertyChanging();
					this._prod_type_no = value;
					this.SendPropertyChanged("prod_type_no");
					this.Onprod_type_noChanged();
				}
			}
		}
		
		[Association(Name="product_prod_dep", Storage="_prod_dep", ThisKey="prod_no", OtherKey="prod_no")]
		public EntitySet<prod_dep> prod_dep
		{
			get
			{
				return this._prod_dep;
			}
			set
			{
				this._prod_dep.Assign(value);
			}
		}
		
		[Association(Name="product_prod_dep_zjc", Storage="_prod_dep_zjc", ThisKey="prod_no", OtherKey="prod_no")]
		public EntitySet<prod_dep_zjc> prod_dep_zjc
		{
			get
			{
				return this._prod_dep_zjc;
			}
			set
			{
				this._prod_dep_zjc.Assign(value);
			}
		}
		
		[Association(Name="Ware_House_product", Storage="_Ware_House", ThisKey="ware_no", OtherKey="Ware_No", IsForeignKey=true)]
		public Ware_House Ware_House
		{
			get
			{
				return this._Ware_House.Entity;
			}
			set
			{
				Ware_House previousValue = this._Ware_House.Entity;
				if (((previousValue != value) 
							|| (this._Ware_House.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ware_House.Entity = null;
						previousValue.product.Remove(this);
					}
					this._Ware_House.Entity = value;
					if ((value != null))
					{
						value.product.Add(this);
						this._ware_no = value.Ware_No;
					}
					else
					{
						this._ware_no = default(string);
					}
					this.SendPropertyChanged("Ware_House");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_prod_dep(prod_dep entity)
		{
			this.SendPropertyChanging();
			entity.product = this;
		}
		
		private void detach_prod_dep(prod_dep entity)
		{
			this.SendPropertyChanging();
			entity.product = null;
		}
		
		private void attach_prod_dep_zjc(prod_dep_zjc entity)
		{
			this.SendPropertyChanging();
			entity.product = this;
		}
		
		private void detach_prod_dep_zjc(prod_dep_zjc entity)
		{
			this.SendPropertyChanging();
			entity.product = null;
		}
	}
	
	[Table(Name="dbo.prod_dep")]
	public partial class prod_dep : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _prod_no;
		
		private string _prod_add;
		
		private string _batch_no;
		
		private decimal _lest_num;
		
		private string _Box_Num;
		
		private System.Nullable<System.DateTime> _avail_date;
		
		private EntityRef<product> _product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprod_noChanging(string value);
    partial void Onprod_noChanged();
    partial void Onprod_addChanging(string value);
    partial void Onprod_addChanged();
    partial void Onbatch_noChanging(string value);
    partial void Onbatch_noChanged();
    partial void Onlest_numChanging(decimal value);
    partial void Onlest_numChanged();
    partial void OnBox_NumChanging(string value);
    partial void OnBox_NumChanged();
    partial void Onavail_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onavail_dateChanged();
    #endregion
		
		public prod_dep()
		{
			this._product = default(EntityRef<product>);
			OnCreated();
		}
		
		[Column(Storage="_prod_no", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string prod_no
		{
			get
			{
				return this._prod_no;
			}
			set
			{
				if ((this._prod_no != value))
				{
					if (this._product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprod_noChanging(value);
					this.SendPropertyChanging();
					this._prod_no = value;
					this.SendPropertyChanged("prod_no");
					this.Onprod_noChanged();
				}
			}
		}
		
		[Column(Storage="_prod_add", DbType="Char(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string prod_add
		{
			get
			{
				return this._prod_add;
			}
			set
			{
				if ((this._prod_add != value))
				{
					this.Onprod_addChanging(value);
					this.SendPropertyChanging();
					this._prod_add = value;
					this.SendPropertyChanged("prod_add");
					this.Onprod_addChanged();
				}
			}
		}
		
		[Column(Storage="_batch_no", DbType="Char(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string batch_no
		{
			get
			{
				return this._batch_no;
			}
			set
			{
				if ((this._batch_no != value))
				{
					this.Onbatch_noChanging(value);
					this.SendPropertyChanging();
					this._batch_no = value;
					this.SendPropertyChanged("batch_no");
					this.Onbatch_noChanged();
				}
			}
		}
		
		[Column(Storage="_lest_num", DbType="Decimal(9,3) NOT NULL")]
		public decimal lest_num
		{
			get
			{
				return this._lest_num;
			}
			set
			{
				if ((this._lest_num != value))
				{
					this.Onlest_numChanging(value);
					this.SendPropertyChanging();
					this._lest_num = value;
					this.SendPropertyChanged("lest_num");
					this.Onlest_numChanged();
				}
			}
		}
		
		[Column(Storage="_Box_Num", DbType="Char(20)")]
		public string Box_Num
		{
			get
			{
				return this._Box_Num;
			}
			set
			{
				if ((this._Box_Num != value))
				{
					this.OnBox_NumChanging(value);
					this.SendPropertyChanging();
					this._Box_Num = value;
					this.SendPropertyChanged("Box_Num");
					this.OnBox_NumChanged();
				}
			}
		}
		
		[Column(Storage="_avail_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> avail_date
		{
			get
			{
				return this._avail_date;
			}
			set
			{
				if ((this._avail_date != value))
				{
					this.Onavail_dateChanging(value);
					this.SendPropertyChanging();
					this._avail_date = value;
					this.SendPropertyChanged("avail_date");
					this.Onavail_dateChanged();
				}
			}
		}
		
		[Association(Name="product_prod_dep", Storage="_product", ThisKey="prod_no", OtherKey="prod_no", IsForeignKey=true)]
		public product product
		{
			get
			{
				return this._product.Entity;
			}
			set
			{
				product previousValue = this._product.Entity;
				if (((previousValue != value) 
							|| (this._product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product.Entity = null;
						previousValue.prod_dep.Remove(this);
					}
					this._product.Entity = value;
					if ((value != null))
					{
						value.prod_dep.Add(this);
						this._prod_no = value.prod_no;
					}
					else
					{
						this._prod_no = default(string);
					}
					this.SendPropertyChanged("product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Ware_House")]
	public partial class Ware_House : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ware_No;
		
		private string _Ware_Name;
		
		private string _Floor_No;
		
		private string _group_no;
		
		private EntitySet<product> _product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWare_NoChanging(string value);
    partial void OnWare_NoChanged();
    partial void OnWare_NameChanging(string value);
    partial void OnWare_NameChanged();
    partial void OnFloor_NoChanging(string value);
    partial void OnFloor_NoChanged();
    partial void Ongroup_noChanging(string value);
    partial void Ongroup_noChanged();
    #endregion
		
		public Ware_House()
		{
			this._product = new EntitySet<product>(new Action<product>(this.attach_product), new Action<product>(this.detach_product));
			OnCreated();
		}
		
		[Column(Storage="_Ware_No", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ware_No
		{
			get
			{
				return this._Ware_No;
			}
			set
			{
				if ((this._Ware_No != value))
				{
					this.OnWare_NoChanging(value);
					this.SendPropertyChanging();
					this._Ware_No = value;
					this.SendPropertyChanged("Ware_No");
					this.OnWare_NoChanged();
				}
			}
		}
		
		[Column(Storage="_Ware_Name", DbType="Char(10)")]
		public string Ware_Name
		{
			get
			{
				return this._Ware_Name;
			}
			set
			{
				if ((this._Ware_Name != value))
				{
					this.OnWare_NameChanging(value);
					this.SendPropertyChanging();
					this._Ware_Name = value;
					this.SendPropertyChanged("Ware_Name");
					this.OnWare_NameChanged();
				}
			}
		}
		
		[Column(Storage="_Floor_No", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Floor_No
		{
			get
			{
				return this._Floor_No;
			}
			set
			{
				if ((this._Floor_No != value))
				{
					this.OnFloor_NoChanging(value);
					this.SendPropertyChanging();
					this._Floor_No = value;
					this.SendPropertyChanged("Floor_No");
					this.OnFloor_NoChanged();
				}
			}
		}
		
		[Column(Storage="_group_no", DbType="Char(2)")]
		public string group_no
		{
			get
			{
				return this._group_no;
			}
			set
			{
				if ((this._group_no != value))
				{
					this.Ongroup_noChanging(value);
					this.SendPropertyChanging();
					this._group_no = value;
					this.SendPropertyChanged("group_no");
					this.Ongroup_noChanged();
				}
			}
		}
		
		[Association(Name="Ware_House_product", Storage="_product", ThisKey="Ware_No", OtherKey="ware_no")]
		public EntitySet<product> product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_product(product entity)
		{
			this.SendPropertyChanging();
			entity.Ware_House = this;
		}
		
		private void detach_product(product entity)
		{
			this.SendPropertyChanging();
			entity.Ware_House = null;
		}
	}
	
	[Table(Name="dbo.prod_dep_zjc")]
	public partial class prod_dep_zjc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _prod_no;
		
		private string _prod_add;
		
		private string _batch_no;
		
		private decimal _lest_num;
		
		private string _Box_Num;
		
		private System.Nullable<System.DateTime> _avail_date;
		
		private EntityRef<product> _product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onprod_noChanging(string value);
    partial void Onprod_noChanged();
    partial void Onprod_addChanging(string value);
    partial void Onprod_addChanged();
    partial void Onbatch_noChanging(string value);
    partial void Onbatch_noChanged();
    partial void Onlest_numChanging(decimal value);
    partial void Onlest_numChanged();
    partial void OnBox_NumChanging(string value);
    partial void OnBox_NumChanged();
    partial void Onavail_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onavail_dateChanged();
    #endregion
		
		public prod_dep_zjc()
		{
			this._product = default(EntityRef<product>);
			OnCreated();
		}
		
		[Column(Storage="_prod_no", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string prod_no
		{
			get
			{
				return this._prod_no;
			}
			set
			{
				if ((this._prod_no != value))
				{
					if (this._product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onprod_noChanging(value);
					this.SendPropertyChanging();
					this._prod_no = value;
					this.SendPropertyChanged("prod_no");
					this.Onprod_noChanged();
				}
			}
		}
		
		[Column(Storage="_prod_add", DbType="Char(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string prod_add
		{
			get
			{
				return this._prod_add;
			}
			set
			{
				if ((this._prod_add != value))
				{
					this.Onprod_addChanging(value);
					this.SendPropertyChanging();
					this._prod_add = value;
					this.SendPropertyChanged("prod_add");
					this.Onprod_addChanged();
				}
			}
		}
		
		[Column(Storage="_batch_no", DbType="Char(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string batch_no
		{
			get
			{
				return this._batch_no;
			}
			set
			{
				if ((this._batch_no != value))
				{
					this.Onbatch_noChanging(value);
					this.SendPropertyChanging();
					this._batch_no = value;
					this.SendPropertyChanged("batch_no");
					this.Onbatch_noChanged();
				}
			}
		}
		
		[Column(Storage="_lest_num", DbType="Decimal(9,3) NOT NULL")]
		public decimal lest_num
		{
			get
			{
				return this._lest_num;
			}
			set
			{
				if ((this._lest_num != value))
				{
					this.Onlest_numChanging(value);
					this.SendPropertyChanging();
					this._lest_num = value;
					this.SendPropertyChanged("lest_num");
					this.Onlest_numChanged();
				}
			}
		}
		
		[Column(Storage="_Box_Num", DbType="Char(20)")]
		public string Box_Num
		{
			get
			{
				return this._Box_Num;
			}
			set
			{
				if ((this._Box_Num != value))
				{
					this.OnBox_NumChanging(value);
					this.SendPropertyChanging();
					this._Box_Num = value;
					this.SendPropertyChanged("Box_Num");
					this.OnBox_NumChanged();
				}
			}
		}
		
		[Column(Storage="_avail_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> avail_date
		{
			get
			{
				return this._avail_date;
			}
			set
			{
				if ((this._avail_date != value))
				{
					this.Onavail_dateChanging(value);
					this.SendPropertyChanging();
					this._avail_date = value;
					this.SendPropertyChanged("avail_date");
					this.Onavail_dateChanged();
				}
			}
		}
		
		[Association(Name="product_prod_dep_zjc", Storage="_product", ThisKey="prod_no", OtherKey="prod_no", IsForeignKey=true)]
		public product product
		{
			get
			{
				return this._product.Entity;
			}
			set
			{
				product previousValue = this._product.Entity;
				if (((previousValue != value) 
							|| (this._product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product.Entity = null;
						previousValue.prod_dep_zjc.Remove(this);
					}
					this._product.Entity = value;
					if ((value != null))
					{
						value.prod_dep_zjc.Add(this);
						this._prod_no = value.prod_no;
					}
					else
					{
						this._prod_no = default(string);
					}
					this.SendPropertyChanged("product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
